apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: crossplane-argocd-vpc
  labels:
    salvamiguel/crossplane-argocd-workshop: vpc
spec:
  forProvider:
    cidrBlock: 10.1.0.0/24
    region: eu-west-3
    tags:
      Name: crossplane-argocd-vpc
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  labels:
    salvamiguel/crossplane-argocd-workshop: subnet-a
  name: crossplane-argocd-subnet-1
spec:
  forProvider:
    availabilityZone: eu-west-3a
    cidrBlock: 10.1.0.0/28
    region: eu-west-3
    vpcIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: vpc
    tags:
      Name: crossplane-subnet-a
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  labels:
    salvamiguel/crossplane-argocd-workshop: subnet-b
  name: crossplane-argocd-subnet-2
spec:
  forProvider:
    availabilityZone: eu-west-3b
    cidrBlock: 10.1.0.16/28
    region: eu-west-3
    vpcIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: vpc
    tags:
      Name: crossplane-subnet-b
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: crossplane-argocd-internet-gw
  labels:
    salvamiguel/crossplane-argocd-workshop: igw
spec:
  forProvider:
    region: eu-west-3
    tags:
      Name: crossplane-argocd-internet-gw
      demo: charlasCV
      author: SM
      type: crossplane-argocd
    vpcIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  labels:
    salvamiguel/crossplane-argocd-workshop: route-table
  name: route-table
spec:
  forProvider:
    region: eu-west-3
    tags:
      Name: crossplane-route-table
      demo: charlasCV
      author: SM
      type: crossplane-argocd
    vpcIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: vpc
---
apiVersion: ec2.aws.upbound.io/v1beta2
kind: Route
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta2/route
  name: route
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: igw
    region: eu-west-3
    routeTableIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: route-table
    tags:
      Name: crossplane-route
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  labels:
    salvamiguel/crossplane-argocd-workshop: rta-1
  name: rta-1
spec:
  forProvider:
    region: eu-west-3
    routeTableIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: route-table
    subnetIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: subnet-a
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  labels:
    salvamiguel/crossplane-argocd-workshop: rta-2
  name: rta-2
spec:
  forProvider:
    region: eu-west-3
    routeTableIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: route-table
    subnetIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: subnet-b
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: alb-security-group
  namespace: crossplane-system
  labels:
    salvamiguel/crossplane-argocd-workshop: alb-sg
spec:
  forProvider:
    description: ALB Security Group
    region: eu-west-3
    name: alb-security-group
    vpcIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: vpc
    tags:
      Name: alb-security-group
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: ec2-security-group
  namespace: crossplane-system
  labels:
    salvamiguel/crossplane-argocd-workshop: ec2-sg
spec:
  forProvider:
    description: EC2 Security Group
    region: eu-west-3
    name: ec2-security-group
    vpcIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: vpc
    tags:
      Name: ec2-security-group
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: alb-egress-http
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    type: egress
    fromPort: 80
    toPort: 80
    protocol: tcp
    cidrBlocks:
      - "0.0.0.0/0"
    securityGroupIdRef:
      name: alb-security-group
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: alb-ingress-http
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    type: ingress
    fromPort: 80
    toPort: 80
    protocol: tcp
    cidrBlocks:
      - "0.0.0.0/0"
    securityGroupIdRef:
      name: alb-security-group
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: ec2-ingress-http
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    type: ingress
    fromPort: 80
    toPort: 80
    protocol: tcp
    sourceSecurityGroupIdRef:
      name: alb-security-group
    securityGroupIdRef:
      name: ec2-security-group
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: ec2-egress-all
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    type: egress
    fromPort: 0
    toPort: 0
    protocol: "-1"
    cidrBlocks:
      - "0.0.0.0/0"
    securityGroupIdRef:
      name: ec2-security-group
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta2
kind: LaunchTemplate
metadata:
  name: crossplane-ec2-launch-template
  namespace: crossplane-system
  labels:
    salvamiguel/crossplane-argocd-workshop: launch-template
spec:
  forProvider:
    region: eu-west-3
    name: crossplane-ec2-launch-template
    versionDescription: "Initial version"
    instanceType: t3.micro
    imageId: ami-03216a20ecc5d72ee
    networkInterfaces:
      - deviceIndex: 0
        associatePublicIpAddress: true
        securityGroupSelector:
          matchLabels:
            salvamiguel/crossplane-argocd-workshop: ec2-sg
    userData: |
      IyEvYmluL2Jhc2gKc3VkbyBzeXN0ZW1jdGwgZW5hYmxlIGFtYXpvbi1zc20tYWdlbnQKc3VkbyBzeXN0ZW1jdGwgc3RhcnQgYW1hem9uLXNzbS1hZ2VudAp5dW0gaW5zdGFsbCAteSBodHRwZAplY2hvICI8aDE+SGVsbG8gZnJvbSAkKGhvc3RuYW1lKTwvaDE+IiA+IC92YXIvd3d3L2h0bWwvaW5kZXguaHRtbApzeXN0ZW1jdGwgc3RhcnQgaHR0cGQKc3lzdGVtY3RsIGVuYWJsZSBodHRwZA==
    tags:
      Name: crossplane-ec2-launch-template
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: autoscaling.aws.upbound.io/v1beta3
kind: AutoscalingGroup
metadata:
  name: crossplane-ec2-auto-scaling-group
  namespace: crossplane-system
spec:
  forProvider:
    vpcZoneIdentifierRefs:
      - name: crossplane-argocd-subnet-1
      - name: crossplane-argocd-subnet-2
    region: eu-west-3
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    launchTemplate:
      idSelector:
        matchLabel:
          salvamiguel/crossplane-argocd-workshop: launch-template
    tag:
      - key: Name
        value: crossplane-argocd-static-web-ec2
        propagateAtLaunch: true
      - key: demo
        value: charlasCV
        propagateAtLaunch: true
      - key: type
        value: crossplane-argocd
        propagateAtLaunch: true
    tags:
      - demo: charlasCV
      - author: SM
      - type: crossplane-argocd
---
apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LB
metadata:
  name: crossplane-alb
  namespace: crossplane-system
spec:
  forProvider:
    name: crossplane-alb
    type: application
    region: eu-west-3
    securityGroupRefs:
      - name: alb-security-group
    subnetRefs:
      - name: crossplane-argocd-subnet-1
      - name: crossplane-argocd-subnet-2
    tags:
      Name: crossplane-alb
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBTargetGroup
metadata:
  labels:
    testing.upbound.io/example-name: elbv2
  name: crossplane-target-group
spec:
  forProvider:
    name: crossplane-target-group
    port: 80
    protocol: HTTP
    region: eu-west-3
    targetType: instance
    vpcIdSelector:
      matchLabels:
        salvamiguel/crossplane-argocd-workshop: vpc
    tags:
      Name: crossplane-target-group
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBListener
metadata:
  name: alb-listener-http
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    loadBalancerArnRef:
      name: crossplane-alb
    port: 80
    protocol: HTTP
    defaultAction:
      - type: forward
        targetGroupArnRef:
          name: crossplane-target-group
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: autoscaling.aws.upbound.io/v1beta2
kind: Attachment
metadata:
  annotations:
    meta.upbound.io/example-id: autoscaling/v1beta2/attachment
  labels:
    testing.upbound.io/example-name: example
  name: crossplane-attachment-asg-elb
spec:
  forProvider:
    autoscalingGroupName: crossplane-ec2-auto-scaling-group
    lbTargetGroupArnRef:
      name: crossplane-target-group
    region: eu-west-3
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
