apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: alb-security-group
  namespace: crossplane-system
spec:
  forProvider:
    description: ALB Security Group
    region: eu-west-3
    name: alb-security-group
    tags:
      Name: alb-security-group
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: ec2-security-group
  namespace: crossplane-system
spec:
  forProvider:
    description: EC2 Security Group
    region: eu-west-3
    name: ec2-security-group
    tags:
      Name: ec2-security-group
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: alb-ingress-http
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    type: ingress
    fromPort: 80
    toPort: 80
    protocol: tcp
    cidrBlocks:
      - "0.0.0.0/0"
    securityGroupIdRef:
      name: alb-security-group
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: alb-ingress-https
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    type: ingress
    fromPort: 443
    toPort: 443
    protocol: tcp
    cidrBlocks:
      - "0.0.0.0/0"
    securityGroupIdRef:
      name: alb-security-group
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: ec2-ingress-http
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    type: ingress
    fromPort: 80
    toPort: 80
    protocol: tcp
    sourceSecurityGroupIdRef:
      name: alb-security-group
    securityGroupIdRef:
      name: ec2-security-group
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: ec2-ingress-https
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    type: ingress
    fromPort: 443
    toPort: 443
    protocol: tcp
    sourceSecurityGroupIdRef:
      name: alb-security-group
    securityGroupIdRef:
      name: ec2-security-group
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: ec2-egress-all
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    type: egress
    fromPort: 0
    toPort: 0
    protocol: "-1"
    cidrBlocks:
      - "0.0.0.0/0"
    securityGroupIdRef:
      name: ec2-security-group
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: LaunchTemplate
metadata:
  name: crossplane-ec2-launch-template
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    name: crossplane-ec2-launch-template
    versionDescription: "Initial version"
    launchTemplateData:
      instanceType: t3.micro
      imageId: resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
      securityGroupNameRef:
        name: ec2-security-group
      userData: |
        #!/bin/bash
        yum install -y httpd
        echo "<h1>Hello from $(hostname)</h1>" > /var/www/html/index.html
        systemctl start httpd
        systemctl enable httpd
    tags:
      Name: crossplane-ec2-launch-template
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: autoscaling.aws.upbound.io/v1beta1
kind: LaunchConfiguration
metadata:
  name: crossplane-ec2-launch-configuration
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    instanceType: t3.micro
    imageId: ami-03216a20ecc5d72ee
    securityGroups:
      - ec2-security-group
    userData: |
      #!/bin/bash
      yum install -y httpd
      echo "<h1>Hello from $(hostname)</h1>" > /var/www/html/index.html
      systemctl start httpd
      systemctl enable httpd
    tags:
      Name: crossplane-ec2-launch-configuration
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: autoscaling.aws.upbound.io/v1beta1
kind: AutoscalingGroup
metadata:
  name: crossplane-ec2-auto-scaling-group
  namespace: crossplane-system
spec:
  forProvider:
    availabilityZones:
      - eu-west-3c
    region: eu-west-3
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    launchConfiguration: crossplane-ec2-launch-configuration
    tag:
      - key: Name
        value: crossplane-argocd-static-web-ec2
        propagateAtLaunch: true
    tags:
      - demo: charlasCV
      - author: SM
      - type: crossplane-argocd
---
apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LB
metadata:
  name: crossplane-application-load-balancer
  namespace: crossplane-system
spec:
  forProvider:
    name: crossplane-application-load-balancer
    type: application
    region: eu-west-3
    securityGroupRefs:
      - name: alb-security-group
    subnets:
      - subnet-0a5969dabf479019b
      - subnet-3e96d673
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
---
apiVersion: autoscaling.aws.upbound.io/v1beta2
kind: Attachment
metadata:
  annotations:
    meta.upbound.io/example-id: autoscaling/v1beta2/attachment
  labels:
    testing.upbound.io/example-name: example
  name: crossplane-asg-elb-attachement
spec:
  forProvider:
    autoscalingGroupName: crossplane-ec2-auto-scaling-group
    elb: crossplane-application-load-balancer
    region: eu-west-3
---
apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBListener
metadata:
  name: alb-listener-http
  namespace: crossplane-system
spec:
  forProvider:
    region: eu-west-3
    loadBalancerArnRef:
      name: crossplane-application-load-balancer
    port: 80
    protocol: HTTP
    defaultAction:
      - type: forward
        targetGroupArnRef:
          name: crossplane-ec2-elb-target-group
    tags:
      demo: charlasCV
      author: SM
      type: crossplane-argocd
